import crypto from 'node:crypto';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import pLimit from 'p-limit';
import sharp from 'sharp';
import { removeBackground } from '@imgly/background-removal-node';

const PORT = Number(process.env.PORT || 3000);
const MAX_UPLOAD_MB = Math.max(1, Number(process.env.MAX_UPLOAD_MB || 20));
const MAX_PROCESSING_SIDE = Math.min(
  1400,
  Math.max(768, Number(process.env.MAX_PROCESSING_SIDE || 1200))
);
const MAX_CONCURRENT = Math.max(1, Number(process.env.MAX_CONCURRENT || 1));
const BACKGROUND_MODEL_RAW = String(process.env.BACKGROUND_MODEL || 'medium').toLowerCase();
const BACKGROUND_MODEL = ['small', 'medium', 'large'].includes(BACKGROUND_MODEL_RAW)
  ? BACKGROUND_MODEL_RAW
  : 'medium';
const ALLOWED_ORIGINS = String(process.env.ALLOWED_ORIGINS || '*')
  .split(',')
  .map(v => v.trim())
  .filter(Boolean);

const app = express();
app.set('trust proxy', 1);

// CORS must be registered before any API/error response so Shopify always gets
// Access-Control-Allow-Origin, including 4xx/5xx responses generated by Express.
app.use(cors({
  origin(origin, callback) {
    if (!origin || ALLOWED_ORIGINS.includes('*') || ALLOWED_ORIGINS.includes(origin)) {
      callback(null, true);
      return;
    }
    callback(new Error('Origin is not allowed by CORS'));
  },
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Accept', 'X-Requested-With'],
  exposedHeaders: ['X-PP3D-Request-Id', 'X-PP3D-Processing-Ms', 'X-PP3D-Pipeline']
}));
app.options('*', cors());

app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(express.json({ limit: '256kb' }));
app.use(rateLimit({
  windowMs: 60_000,
  limit: Number(process.env.RATE_LIMIT_PER_MINUTE || 30),
  standardHeaders: 'draft-7',
  legacyHeaders: false
}));

const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: MAX_UPLOAD_MB * 1024 * 1024,
    files: 1
  },
  fileFilter(_req, file, cb) {
    const ok = new Set(['image/jpeg', 'image/png', 'image/webp']).has(file.mimetype);
    if (!ok) {
      cb(new Error('UNSUPPORTED_IMAGE_TYPE'));
      return;
    }
    cb(null, true);
  }
});

const runLimited = pLimit(MAX_CONCURRENT);

function requestId() {
  return crypto.randomBytes(8).toString('hex');
}

async function normalizeImage(inputBuffer) {
  return sharp(inputBuffer, { failOn: 'warning', sequentialRead: true })
    .rotate()
    .resize({
      width: MAX_PROCESSING_SIDE,
      height: MAX_PROCESSING_SIDE,
      fit: 'inside',
      withoutEnlargement: true,
      kernel: sharp.kernel.lanczos3
    })
    .png({ compressionLevel: 5, adaptiveFiltering: true })
    .toBuffer();
}

async function hasUsefulTransparency(buffer) {
  const { data, info } = await sharp(buffer, { sequentialRead: true })
    .ensureAlpha()
    .resize({
      width: 180,
      height: 180,
      fit: 'inside',
      withoutEnlargement: true
    })
    .raw()
    .toBuffer({ resolveWithObject: true });

  let transparent = 0;
  const pixels = info.width * info.height;
  for (let i = 3; i < data.length; i += 4) {
    if (data[i] < 240) transparent++;
  }
  return pixels > 0 && transparent / pixels > 0.025;
}

async function removeBackgroundServer(buffer) {
  const input = new Blob([buffer], { type: 'image/png' });
  const output = await removeBackground(input, {
    debug: false,
    model: BACKGROUND_MODEL,
    proxyToWorker: false,
    output: {
      format: 'image/png',
      quality: 1,
      type: 'foreground'
    }
  });
  return Buffer.from(await output.arrayBuffer());
}

async function cropTransparentLikeShopify(buffer) {
  const { data, info } = await sharp(buffer, { sequentialRead: true })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const { width, height, channels } = info;
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const alpha = data[(y * width + x) * channels + 3];
      if (alpha > 28) {
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
      }
    }
  }

  if (maxX < minX || maxY < minY) {
    throw new Error('SUBJECT_NOT_FOUND');
  }

  const w0 = maxX - minX + 1;
  const h0 = maxY - minY + 1;
  const pad = Math.max(2, Math.round(Math.max(w0, h0) * 0.012));

  minX = Math.max(0, minX - pad);
  minY = Math.max(0, minY - pad);
  maxX = Math.min(width - 1, maxX + pad);
  maxY = Math.min(height - 1, maxY + pad);

  return sharp(buffer, { sequentialRead: true })
    .extract({
      left: minX,
      top: minY,
      width: maxX - minX + 1,
      height: maxY - minY + 1
    })
    .png({ compressionLevel: 5, adaptiveFiltering: true })
    .toBuffer();
}

async function processPillow(inputBuffer) {
  const started = Date.now();

  // IMPORTANT: this stable Railway build intentionally does NOT load DETR or
  // any second AI model in the same Node process. The previous build was being
  // OOM-killed after holding DETR and IMG.LY at the same time. IMG.LY receives
  // the full normalized photo, so people/pet groups are not discarded by a
  // single-object detector. Desktop and mobile therefore use the exact same
  // server pipeline and receive the exact same processed PNG for the same file.
  const normalized = await normalizeImage(inputBuffer);

  let foreground = normalized;
  if (!(await hasUsefulTransparency(normalized))) {
    foreground = await removeBackgroundServer(normalized);
  }

  const finalPng = await cropTransparentLikeShopify(foreground);

  return {
    buffer: finalPng,
    elapsedMs: Date.now() - started
  };
}

app.get('/', (_req, res) => {
  res.json({
    ok: true,
    service: 'TAZROX Pillow Processing API',
    version: '1.1.0',
    pipeline: 'imgly-full-image-low-memory'
  });
});

app.get('/health', (_req, res) => {
  res.json({
    ok: true,
    maxProcessingSide: MAX_PROCESSING_SIDE,
    maxConcurrent: MAX_CONCURRENT,
    backgroundModel: BACKGROUND_MODEL,
    detector: 'disabled',
    samePipelineForDesktopAndMobile: true,
    pipeline: 'imgly-full-image-low-memory'
  });
});

app.post('/api/process-pillow', upload.single('image'), async (req, res, next) => {
  const id = requestId();
  res.setHeader('X-PP3D-Request-Id', id);
  res.setHeader('X-PP3D-Pipeline', 'imgly-full-image-low-memory');

  try {
    if (!req.file?.buffer) {
      res.status(400).json({
        ok: false,
        code: 'IMAGE_REQUIRED',
        message: 'Upload an image using the multipart field named "image".'
      });
      return;
    }

    const result = await runLimited(() => processPillow(req.file.buffer));

    res.setHeader('Content-Type', 'image/png');
    res.setHeader('Content-Disposition', 'inline; filename="pillow-cutout.png"');
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('X-PP3D-Processing-Ms', String(result.elapsedMs));
    res.status(200).send(result.buffer);
  } catch (error) {
    error.requestId = id;
    next(error);
  }
});

app.use((error, _req, res, _next) => {
  console.error('PP3D SERVER ERROR:', error);

  let status = 500;
  let code = 'SERVER_PROCESSING_FAILED';
  let message = 'The server could not process this photo. Please try again.';

  if (error?.code === 'LIMIT_FILE_SIZE') {
    status = 413;
    code = 'IMAGE_TOO_LARGE';
    message = `The image is larger than ${MAX_UPLOAD_MB}MB.`;
  } else if (String(error?.message || '').includes('UNSUPPORTED_IMAGE_TYPE')) {
    status = 415;
    code = 'UNSUPPORTED_IMAGE_TYPE';
    message = 'Please upload a JPG, PNG, or WebP image.';
  } else if (String(error?.message || '').includes('SUBJECT_NOT_FOUND')) {
    status = 422;
    code = 'SUBJECT_NOT_FOUND';
    message = 'We could not clearly separate the subject from this photo.';
  } else if (String(error?.message || '').includes('CORS')) {
    status = 403;
    code = 'ORIGIN_NOT_ALLOWED';
    message = 'This Shopify domain is not allowed to use the processing API.';
  }

  res.status(status).json({
    ok: false,
    code,
    message,
    requestId: error?.requestId || null
  });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`TAZROX Pillow Processing API v1.1.0 listening on port ${PORT}`);
  console.log(`Allowed origins: ${ALLOWED_ORIGINS.join(', ')}`);
  console.log(`Max upload: ${MAX_UPLOAD_MB}MB`);
  console.log(`Max processing side: ${MAX_PROCESSING_SIDE}px`);
  console.log(`Concurrency: ${MAX_CONCURRENT}`);
  console.log(`Background model: ${BACKGROUND_MODEL}`);
  console.log('Detector: disabled (low-memory stable pipeline)');
});
